# texts.py
TEXTS = {
    'ar': {
        'welcome': "🎉 مرحباً بك في بوت إدارة الجروبات المتطور!\n\n🤖 هذا البوت يساعدك في إدارة جروباتك تلقائياً مع نظام الاشتراك الإجباري في القنوات.",
        'main_menu': "🤖 **البوت المتطور لإدارة الجروبات**\n\nاختر أحد الخيارات التالية:",
        'language_changed': "✅ تم تغيير اللغة إلى العربية بنجاح!",
        'add_group': "📝 لإضافة جروب جديد:\n\n1. أضف البوت كأدمن في الجروب\n2. امنحه صلاحية حذف الرسائل\n3. أرسل معرف الجروب أو الرابط",
        'enter_group_username': "🔗 أرسل معرف الجروب (مثال: @group_username) أو الرابط:",
        'group_added_success': "✅ تم إضافة الجروب بنجاح!\n\n📝 الآن قم بإعداد الكلمة المفتاحية للجروب:",
        'enter_keyword': "🔑 أرسل الكلمة المفتاحية للجروب (سيتم مراقبة الرسائل التي تحتوي على هذه الكلمة):",
        'keyword_set_success': "✅ تم تعيين الكلمة المفتاحية بنجاح!\n\n📢 هل تريد إضافة قناة مخصصة للاشتراك الإجباري؟",
        'add_channel_question': "📢 هل تريد إضافة قناة مخصصة للاشتراك الإجباري؟\n\nإذا كنت تريد استخدام القناة الافتراضية فقط، اضغط 'تخطي'",
        'enter_channel_username': "🔗 أرسل معرف القناة (مثال: @channel_username):",
        'channel_added_success': "✅ تم إضافة القناة بنجاح!\n\n🎉 تم تكوين الجروب بالكامل وجاهز للعمل!",
        'setup_complete': "🎉 تم تكوين الجروب بالكامل وجاهز للعمل!",
        'skip_channel': "⏭️ تم تخطي إضافة قناة مخصصة. سيستخدم الجروب القناة الافتراضية.",
        'active_groups': "📊 **الجروبات النشطة:**\n\n",
        'no_active_groups': "❌ لا توجد جروبات نشطة حالياً.",
        'group_item': "🔹 **{group_name}**\n   📝 الكلمة: {keyword}\n   🌐 اللغة: {language}\n\n",
        'stats': "📊 **إحصائيات البوت:**\n\n",
        'stats_groups': "👥 الجروبات النشطة: {active_groups}",
        'stats_deleted': "🗑️ الرسائل المحذوفة: {deleted_messages}",
        'stats_users': "👤 المستخدمين: {total_users}",
        'check_subscription': "🔍 تحقق من اشتراكك في القناة المطلوبة:",
        'not_subscribed': "❌ **عذراً!**\n\nيجب عليك الاشتراك في القناة التالية أولاً:\n{channel}\n\nبعد الاشتراك، اضغط على زر 'تحقق من الاشتراك'",
        'subscribed': "✅ **مبروك!**\n\nأنت مشترك في القناة المطلوبة.\nيمكنك الآن استخدام البوت.",
        'still_not_subscribed': "❌ **لم يتم الاشتراك بعد**\n\nيجب الاشتراك في القناة أولاً:\n{channel}",
        'change_language': "🌐 اختر اللغة:",
        'settings': "⚙️ **الإعدادات:**\n\nاختر الإعداد الذي تريد تعديله:",
        'scan_messages': "🔍 جاري فحص الرسائل في الجروب...",
        'scan_complete': "✅ تم فحص الرسائل بنجاح!",
        'back_to_main': "↩️ العودة إلى القائمة الرئيسية",
        'subscription_warning': "⚠️ **تنبيه!**\n\nعزيزي {user_name}، يجب عليك الاشتراك في القناة التالية:\n{channel}\n\nسيتم حذف رسالتك خلال 3 دقائق.",
        'no_username_warning': "⚠️ **تنبيه!**\n\nعزيزي {user_name}، يجب أن يكون لديك @username في حسابك لإرسال الرسائل في هذا الجروب.",
        'message_deleted': "🗑️ **تم حذف الرسالة**\n\nالسبب: {reason}",
        'bot_not_admin': "❌ البوت ليس أدمن في الجروب! يرجى إضافة البوت كأدمن مع صلاحية حذف الرسائل.",
        'invalid_group': "❌ رابط الجروب غير صحيح! تأكد من إرسال معرف الجروب أو الرابط بشكل صحيح.",
        'error_occurred': "❌ حدث خطأ ما! يرجى المحاولة مرة أخرى.",
        'processing': "⏳ جاري المعالجة...",
    },
    'en': {
        'welcome': "🎉 Welcome to Advanced Group Manager Bot!\n\n🤖 This bot helps you manage your groups automatically with mandatory channel subscription system.",
        'main_menu': "🤖 **Advanced Group Management Bot**\n\nChoose one of the following options:",
        'language_changed': "✅ Language changed to English successfully!",
        'add_group': "📝 To add a new group:\n\n1. Add bot as admin in the group\n2. Give it delete messages permission\n3. Send group username or link",
        'enter_group_username': "🔗 Send group username (e.g., @group_username) or link:",
        'group_added_success': "✅ Group added successfully!\n\n📝 Now set the keyword for the group:",
        'enter_keyword': "🔑 Send the group keyword (messages containing this word will be monitored):",
        'keyword_set_success': "✅ Keyword set successfully!\n\n📢 Do you want to add a custom channel for mandatory subscription?",
        'add_channel_question': "📢 Do you want to add a custom channel for mandatory subscription?\n\nIf you want to use only the default channel, click 'Skip'",
        'enter_channel_username': "🔗 Send channel username (e.g., @channel_username):",
        'channel_added_success': "✅ Channel added successfully!\n\n🎉 Group setup completed and ready to work!",
        'setup_complete': "🎉 Group setup completed and ready to work!",
        'skip_channel': "⏭️ Custom channel skipped. Group will use default channel.",
        'active_groups': "📊 **Active Groups:**\n\n",
        'no_active_groups': "❌ No active groups currently.",
        'group_item': "🔹 **{group_name}**\n   📝 Keyword: {keyword}\n   🌐 Language: {language}\n\n",
        'stats': "📊 **Bot Statistics:**\n\n",
        'stats_groups': "👥 Active Groups: {active_groups}",
        'stats_deleted': "🗑️ Deleted Messages: {deleted_messages}",
        'stats_users': "👤 Users: {total_users}",
        'check_subscription': "🔍 Check your subscription to the required channel:",
        'not_subscribed': "❌ **Sorry!**\n\nYou must subscribe to the following channel first:\n{channel}\n\nAfter subscribing, click the 'Check Subscription' button",
        'subscribed': "✅ **Congratulations!**\n\nYou are subscribed to the required channel.\nYou can now use the bot.",
        'still_not_subscribed': "❌ **Not subscribed yet**\n\nYou must subscribe to the channel first:\n{channel}",
        'change_language': "🌐 Choose language:",
        'settings': "⚙️ **Settings:**\n\nChoose the setting you want to modify:",
        'scan_messages': "🔍 Scanning messages in group...",
        'scan_complete': "✅ Messages scanned successfully!",
        'back_to_main': "↩️ Back to main menu",
        'subscription_warning': "⚠️ **Warning!**\n\nDear {user_name}, you must subscribe to the following channel:\n{channel}\n\nYour message will be deleted in 3 minutes.",
        'no_username_warning': "⚠️ **Warning!**\n\nDear {user_name}, you must have @username in your account to send messages in this group.",
        'message_deleted': "🗑️ **Message Deleted**\n\nReason: {reason}",
        'bot_not_admin': "❌ Bot is not admin in the group! Please add bot as admin with delete messages permission.",
        'invalid_group': "❌ Invalid group link! Make sure to send group username or link correctly.",
        'error_occurred': "❌ An error occurred! Please try again.",
        'processing': "⏳ Processing...",
    },
    'ru': {
        'welcome': "🎉 Добро пожаловать в Advanced Group Manager Bot!\n\n🤖 Этот бот помогает автоматически управлять вашими группами с системой обязательной подписки на каналы.",
        'main_menu': "🤖 **Продвинутый бот для управления группами**\n\nВыберите одну из следующих опций:",
        'language_changed': "✅ Язык успешно изменен на русский!",
        # ... نصوص روسية أخرى
    },
    'fr': {
        'welcome': "🎉 Bienvenue dans Advanced Group Manager Bot!\n\n🤖 Ce bot vous aide à gérer automatiquement vos groupes avec un système d'abonnement obligatoire aux chaînes.",
        'main_menu': "🤖 **Bot de gestion de groupe avancé**\n\nChoisissez l'une des options suivantes:",
        'language_changed': "✅ Langue changée en français avec succès!",
        # ... نصوص فرنسية أخرى
    }
}

def get_text(language, key, **kwargs):
    """الحصول على النص بناءً على اللغة والمفتاح"""
    text = TEXTS.get(language, TEXTS['ar']).get(key, TEXTS['ar'].get(key, key))
    return text.format(**kwargs) if kwargs else text
